language: python
python:
  - "3.6.9"
services:
  - postgresql
install:
  - psql -c 'create database eucitizenscience;' -U postgres
  - psql -c "CREATE USER eucitizenscience with password 'eucitizenscience';" -U postgres
  - psql -c 'GRANT ALL PRIVILEGES ON DATABASE eucitizenscience TO eucitizenscience;' -U postgres
  - pip3 install -r requirements.txt
  - cd src
  - cp eucs_platform/settings/local.sample.env eucs_platform/settings/local.env
  - python manage.py migrate
  - python manage.py loaddata projects/fixtures/topics.json
  - python manage.py loaddata projects/fixtures/status.json
  - python manage.py loaddata resources/fixtures/categories.json
  - python manage.py loaddata resources/fixtures/themes.json
  - python manage.py loaddata resources/fixtures/audiences.json
script:
  - python manage.py test profiles
